# General Settings
name: De Gracia Mathieu
job_title: Lead Developer Laravel
email: youremail@gmail.com
description: Lead developer Laravel at Focus Home Interactive. J'accorde de l'importance à la notion de qualité, comment la définir, la propager au sein d'une équipe.
avatar: https://avatars2.githubusercontent.com/u/11473997?s=460&u=52f80e74dccdfc1a723f609c2d1fc81bba6251ae&v=4
favicon: /favicon.ico
twitter_handler: your_handler
analytics_code: UA-XXXXXXX-2
disqus: your_disqus_site

# Social Accounts
social_networks:
-  { name: twitter, url: 'http://twitter.com/degraciamathieu' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/mathieu-de-gracia' }
-  { name: github, url: 'https://github.com/DeGraciaMathieu' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 0
show_rss: 1
show_comments: 0
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "https://justanothertechblog.fr"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed
